export const palette = {
  black: '#0B0B0F',
  nearBlack: '#121218',
  white: '#FFFFFF',
  warmWhite: '#FAFAF7',
  cream: '#F5F3EE',
  offWhite: '#F7F7F4',

  aqua: '#14B8A6',
  aquaDeep: '#0D9488',
  aquaSoft: 'rgba(20, 184, 166, 0.14)',

  coral: '#F97066',
  coralDeep: '#E85D55',
  coralSoft: 'rgba(249, 112, 102, 0.16)',

  lime: '#84CC16',
  limeDeep: '#65A30D',
  limeSoft: 'rgba(132, 204, 22, 0.16)',

  sky: '#38BDF8',
  skyDeep: '#0EA5E9',
  skySoft: 'rgba(56, 189, 248, 0.16)',

  lavender: '#A78BFA',
  lavenderDeep: '#8B5CF6',
  lavenderSoft: 'rgba(167, 139, 250, 0.16)',

  amber: '#F59E0B',
  amberDeep: '#D97706',
  amberSoft: 'rgba(245, 158, 11, 0.16)',

  pink: '#F472B6',
  pinkDeep: '#EC4899',
  pinkSoft: 'rgba(244, 114, 182, 0.16)',

  indigo: '#818CF8',
  indigoDeep: '#6366F1',
  indigoSoft: 'rgba(129, 140, 248, 0.16)',

  cyan: '#22D3EE',
  cyanDeep: '#06B6D4',
  cyanSoft: 'rgba(34, 211, 238, 0.16)',

  like: '#FB7185',
  success: '#22C55E',
  warning: '#F59E0B',
  error: '#EF4444',

  /** @deprecated aliases for gradual migration */
  teal: '#14B8A6',
  tealMuted: '#0D9488',
  tealSoft: 'rgba(20, 184, 166, 0.14)',
  maroon: '#F97066',
  maroonSoft: 'rgba(249, 112, 102, 0.16)',
  green: '#84CC16',
  yellow: '#F59E0B',
  orange: '#FB923C',
  /** Clinical blue for health tree (CliniQ-style). */
  clinical: '#5BB8E8',
  clinicalDeep: '#1E3A5F',
  clinicalSoft: 'rgba(91, 184, 232, 0.18)',
  clinicalNavy: '#1E3A5F',

  gray: {
    50: '#FAFAF8',
    100: '#F3F2EE',
    200: '#E8E6E0',
    300: '#D4D2CB',
    400: '#A8A59C',
    500: '#78756C',
    600: '#5C5952',
    700: '#3F3D38',
    800: '#2A2825',
    850: '#1E1D1B',
    900: '#161514',
    950: '#0C0B0A',
  },
} as const;

export const treeColors = {
  health: {
    accent: palette.clinical,
    soft: palette.clinicalSoft,
    deep: palette.clinicalDeep,
  },
  fitness: {
    accent: palette.lime,
    soft: palette.limeSoft,
    deep: palette.limeDeep,
  },
  sports: {
    accent: palette.sky,
    soft: palette.skySoft,
    deep: palette.skyDeep,
  },
  wellness: {
    accent: palette.lavender,
    soft: palette.lavenderSoft,
    deep: palette.lavenderDeep,
  },
  tours_events: {
    accent: palette.amber,
    soft: palette.amberSoft,
    deep: palette.amberDeep,
  },
  beauty_spa: {
    accent: palette.pink,
    soft: palette.pinkSoft,
    deep: palette.pinkDeep,
  },
  course_training: {
    accent: palette.indigo,
    soft: palette.indigoSoft,
    deep: palette.indigoDeep,
  },
  home_services: {
    accent: palette.cyan,
    soft: palette.cyanSoft,
    deep: palette.cyanDeep,
  },
  ecommerce: {
    accent: palette.amber,
    soft: palette.amberSoft,
    deep: palette.amberDeep,
  },
} as const;

export type TreeColorId = keyof typeof treeColors;

/** Soft wash from a hex accent (approx 14% opacity). */
export function softFill(hex: string, alpha = 0.14): string {
  const raw = hex.replace('#', '');
  if (raw.length !== 6) return hex;
  const r = parseInt(raw.slice(0, 2), 16);
  const g = parseInt(raw.slice(2, 4), 16);
  const b = parseInt(raw.slice(4, 6), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

export const lightColors = {
  background: palette.warmWhite,
  backgroundElevated: palette.white,
  surface: palette.white,
  surfaceSecondary: palette.cream,
  surfaceMuted: palette.gray[100],
  surfaceBright: palette.gray[50],
  surfaceGlass: 'rgba(255,255,255,0.82)',
  textPrimary: palette.gray[900],
  textSecondary: palette.gray[600],
  textTertiary: palette.gray[500],
  textMuted: palette.gray[400],
  textInverse: palette.white,
  textOnSurface: palette.gray[900],
  border: 'rgba(20, 18, 14, 0.08)',
  borderSoft: 'rgba(20, 18, 14, 0.05)',
  borderStrong: 'rgba(20, 18, 14, 0.12)',
  primary: palette.aqua,
  primarySoft: palette.aquaSoft,
  primaryMuted: palette.aquaDeep,
  secondary: palette.coral,
  secondarySoft: palette.coralSoft,
  accent: palette.coral,
  accentSoft: palette.coralSoft,
  like: palette.like,
  link: palette.aquaDeep,
  success: palette.success,
  warning: palette.warning,
  error: palette.error,
  tabBar: palette.white,
  tabIcon: palette.gray[400],
  tabIconActive: palette.aquaDeep,
  overlay: 'rgba(12, 11, 10, 0.4)',
  tile: palette.aquaSoft,
  yellow: palette.yellow,
  green: palette.green,
  orange: palette.orange,
  navy: palette.navy,
  skeleton: 'rgba(20, 18, 14, 0.06)',
  skeletonHighlight: 'rgba(20, 18, 14, 0.1)',
  trees: treeColors,
  health: treeColors.health.accent,
  fitness: treeColors.fitness.accent,
  sports: treeColors.sports.accent,
  wellness: treeColors.wellness.accent,
  travel: treeColors.tours_events.accent,
  beauty: treeColors.beauty_spa.accent,
  courses: treeColors.course_training.accent,
  homeServices: treeColors.home_services.accent,
  ecommerce: treeColors.ecommerce.accent,
};

export const darkColors = {
  background: palette.black,
  backgroundElevated: palette.gray[900],
  surface: palette.gray[850],
  surfaceSecondary: palette.gray[800],
  surfaceMuted: palette.gray[800],
  surfaceBright: palette.gray[700],
  surfaceGlass: 'rgba(30, 29, 27, 0.88)',
  textPrimary: palette.offWhite,
  textSecondary: palette.gray[400],
  textTertiary: palette.gray[500],
  textMuted: palette.gray[500],
  textInverse: palette.black,
  textOnSurface: palette.offWhite,
  border: 'rgba(255,255,255,0.08)',
  borderSoft: 'rgba(255,255,255,0.05)',
  borderStrong: 'rgba(255,255,255,0.14)',
  primary: palette.aqua,
  primarySoft: palette.aquaSoft,
  primaryMuted: palette.aquaDeep,
  secondary: palette.coral,
  secondarySoft: palette.coralSoft,
  accent: palette.coral,
  accentSoft: palette.coralSoft,
  like: palette.like,
  link: palette.aqua,
  success: palette.success,
  warning: palette.warning,
  error: palette.error,
  tabBar: palette.gray[850],
  tabIcon: palette.gray[400],
  tabIconActive: palette.aqua,
  overlay: 'rgba(0, 0, 0, 0.55)',
  tile: palette.aquaSoft,
  yellow: palette.yellow,
  green: palette.green,
  orange: palette.orange,
  navy: palette.navy,
  skeleton: 'rgba(255,255,255,0.06)',
  skeletonHighlight: 'rgba(255,255,255,0.12)',
  trees: treeColors,
  health: treeColors.health.accent,
  fitness: treeColors.fitness.accent,
  sports: treeColors.sports.accent,
  wellness: treeColors.wellness.accent,
  travel: treeColors.tours_events.accent,
  beauty: treeColors.beauty_spa.accent,
  courses: treeColors.course_training.accent,
  homeServices: treeColors.home_services.accent,
  ecommerce: treeColors.ecommerce.accent,
};
