import React from 'react';
import { LucideProps } from 'lucide-react-native';
import {
  Activity,
  Accessibility,
  BadgeCheck,
  Bike,
  Bell,
  Bookmark,
  Brain,
  Calendar,
  Camera,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  CirclePlus,
  Clapperboard,
  ClipboardList,
  Clock,
  Coins,
  CreditCard,
  Droplets,
  Dumbbell,
  Ellipsis,
  Film,
  Flame,
  FlaskConical,
  Footprints,
  Gamepad2,
  Globe,
  GraduationCap,
  HandHelping,
  Heart,
  HeartOff,
  HeartPulse,
  Home,
  Hospital,
  LayoutGrid,
  Leaf,
  Lightbulb,
  Lock,
  MapPin,
  MessageCircle,
  Mic,
  Minus,
  Monitor,
  Moon,
  Mountain,
  Music2,
  Package,
  PartyPopper,
  Pencil,
  Pill,
  Play as PlayIcon,
  Plus,
  Scale,
  Search,
  Send,
  Settings,
  Share2,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Stethoscope,
  TestTube2,
  ThumbsDown,
  ThumbsUp,
  Trophy,
  Trash2,
  Truck,
  User,
  UserPlus,
  Users,
  Video,
  Volume2,
  VolumeX,
  Wrench,
  X,
  Zap,
  Flag,
  Captions,
  ChevronsDown,
} from 'lucide-react-native';

export const iconMap = {
  home: Home,
  reels: Clapperboard,
  clapperboard: Clapperboard,
  play: PlayIcon,
  create: Plus,
  plus: Plus,
  'circle-plus': CirclePlus,
  health: HeartPulse,
  'heart-pulse': HeartPulse,
  shop: ShoppingBag,
  star: Star,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  cart: ShoppingCart,
  profile: User,
  user: User,
  search: Search,
  settings: Settings,
  messages: MessageCircle,
  'message-circle': MessageCircle,
  mic: Mic,
  bell: Bell,
  back: ChevronLeft,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  lock: Lock,
  close: X,
  x: X,
  more: Ellipsis,
  ellipsis: Ellipsis,
  doctor: Stethoscope,
  stethoscope: Stethoscope,
  hospital: Hospital,
  diagnostics: FlaskConical,
  flask: FlaskConical,
  lab: TestTube2,
  'test-tube': TestTube2,
  clipboard: ClipboardList,
  'clipboard-list': ClipboardList,
  coins: Coins,
  clock: Clock,
  music: Music2,
  'music-2': Music2,
  grid: LayoutGrid,
  pharmacy: Pill,
  pill: Pill,
  leaf: Leaf,
  physio: Accessibility,
  accessibility: Accessibility,
  fitness: Dumbbell,
  dumbbell: Dumbbell,
  calendar: Calendar,
  location: MapPin,
  'map-pin': MapPin,
  video: Video,
  'home-visit': Home,
  online: Globe,
  globe: Globe,
  monitor: Monitor,
  steps: Footprints,
  footprints: Footprints,
  sleep: Moon,
  moon: Moon,
  calories: Flame,
  flame: Flame,
  weight: Scale,
  scale: Scale,
  water: Droplets,
  droplet: Droplets,
  activity: Activity,
  heart: Heart,
  'heart-off': HeartOff,
  unlike: ThumbsDown,
  comment: MessageCircle,
  share: Share2,
  send: Send,
  save: Bookmark,
  bookmark: Bookmark,
  follow: UserPlus,
  'user-plus': UserPlus,
  friends: Users,
  users: Users,
  community: Users,
  wishlist: Heart,
  add: Plus,
  remove: Minus,
  minus: Minus,
  payment: CreditCard,
  'credit-card': CreditCard,
  order: Package,
  package: Package,
  delivery: Truck,
  truck: Truck,
  check: Check,
  'check-circle': CheckCircle2,
  'badge-check': BadgeCheck,
  verified: BadgeCheck,
  camera: Camera,
  mountain: Mountain,
  bike: Bike,
  trophy: Trophy,
  trash: Trash2,
  edit: Pencil,
  sparkles: Sparkles,
  wrench: Wrench,
  zap: Zap,
  'graduation-cap': GraduationCap,
  brain: Brain,
  gamepad: Gamepad2,
  smartphone: Smartphone,
  support: HandHelping,
  'hand-helping': HandHelping,
  useful: Lightbulb,
  lightbulb: Lightbulb,
  inspiring: Sparkles,
  celebrate: PartyPopper,
  'party-popper': PartyPopper,
  love: Heart,
  like: Heart,
  film: Film,
  volume: Volume2,
  'volume-2': Volume2,
  unmute: Volume2,
  'volume-x': VolumeX,
  mute: VolumeX,
  flag: Flag,
  report: Flag,
  'thumbs-up': ThumbsUp,
  interested: ThumbsUp,
  captions: Captions,
  caption: Captions,
  'chevrons-down': ChevronsDown,
  'auto-scroll': ChevronsDown,
} as const;

export type IconName = keyof typeof iconMap;

export type AppIconProps = {
  name: IconName | string;
  size?: number;
  color?: string;
  strokeWidth?: number;
  absoluteStrokeWidth?: boolean;
  fill?: string;
} & Omit<LucideProps, 'size' | 'color' | 'strokeWidth' | 'fill'>;

export function AppIcon({
  name,
  size = 22,
  color = '#161514',
  strokeWidth = 1.75,
  absoluteStrokeWidth = false,
  /** Outline by default. Pass a color only when the icon should be solid (e.g. active like). */
  fill = 'none',
  ...rest
}: AppIconProps) {
  const Icon = iconMap[name as IconName];
  if (!Icon && __DEV__) {
    // eslint-disable-next-line no-console
    console.warn(`[AppIcon] Unknown icon "${name}" — using fallback.`);
  }
  const Resolved = Icon ?? Ellipsis;
  return (
    <Resolved
      size={size}
      color={color}
      strokeWidth={strokeWidth}
      absoluteStrokeWidth={absoluteStrokeWidth}
      fill={fill}
      {...rest}
    />
  );
}
