import type { ProviderFormSchemaBody } from '@anticlock/contracts';

const commonSections = [
  { id: 'basic', title: 'Basic details', sortOrder: 1 },
  { id: 'location', title: 'Location', sortOrder: 2 },
  { id: 'profile', title: 'Profile', sortOrder: 3 },
  { id: 'identity', title: 'Identity & verification', sortOrder: 4 },
  { id: 'availability', title: 'Availability', sortOrder: 5 },
  { id: 'services', title: 'Services offered', sortOrder: 6 },
];

const commonFields = [
  {
    key: 'basic.providerName',
    type: 'text' as const,
    label: 'Business / provider name',
    required: true,
    sectionId: 'basic',
  },
  {
    key: 'basic.contactPerson',
    type: 'text' as const,
    label: 'Contact person',
    required: true,
    sectionId: 'basic',
  },
  {
    key: 'basic.mobile',
    type: 'phone' as const,
    label: 'Mobile number',
    required: true,
    sectionId: 'basic',
  },
  {
    key: 'basic.email',
    type: 'email' as const,
    label: 'Email',
    required: true,
    sectionId: 'basic',
  },
  {
    key: 'location.address',
    type: 'textarea' as const,
    label: 'Address',
    required: true,
    sectionId: 'location',
  },
  {
    key: 'location.area',
    type: 'text' as const,
    label: 'Area / locality',
    sectionId: 'location',
  },
  {
    key: 'location.city',
    type: 'text' as const,
    label: 'City',
    required: true,
    sectionId: 'location',
  },
  {
    key: 'location.pincode',
    type: 'text' as const,
    label: 'Pincode',
    required: true,
    sectionId: 'location',
    validation: { pattern: '^[0-9]{6}$' },
  },
  {
    key: 'location.map',
    type: 'location' as const,
    label: 'Map location',
    sectionId: 'location',
  },
  {
    key: 'location.serviceRadiusKm',
    type: 'number' as const,
    label: 'Service radius (km)',
    sectionId: 'location',
  },
  {
    key: 'profile.logo',
    type: 'image' as const,
    label: 'Logo / profile image',
    sectionId: 'profile',
  },
  {
    key: 'profile.coverImages',
    type: 'image' as const,
    label: 'Cover images',
    sectionId: 'profile',
  },
  {
    key: 'profile.introVideo',
    type: 'video' as const,
    label: 'Introduction video',
    sectionId: 'profile',
  },
  {
    key: 'profile.description',
    type: 'textarea' as const,
    label: 'Description',
    sectionId: 'profile',
  },
  {
    key: 'profile.yearsInOperation',
    type: 'number' as const,
    label: 'Years in operation',
    sectionId: 'profile',
  },
  {
    key: 'identity.aadhaarNumber',
    type: 'aadhaar' as const,
    label: 'Aadhaar number',
    required: true,
    sectionId: 'identity',
  },
  {
    key: 'identity.aadhaarDocument',
    type: 'document' as const,
    label: 'Aadhaar document',
    required: true,
    sectionId: 'identity',
  },
  {
    key: 'identity.idDocument',
    type: 'document' as const,
    label: 'Identity document',
    required: true,
    sectionId: 'identity',
  },
  {
    key: 'identity.businessRegistration',
    type: 'document' as const,
    label: 'Business registration',
    sectionId: 'identity',
    visibleWhen: { providerKind: 'business' as const },
  },
  {
    key: 'availability.workingDays',
    type: 'multiselect' as const,
    label: 'Working days',
    required: true,
    sectionId: 'availability',
    options: [
      { value: 'mon', label: 'Monday' },
      { value: 'tue', label: 'Tuesday' },
      { value: 'wed', label: 'Wednesday' },
      { value: 'thu', label: 'Thursday' },
      { value: 'fri', label: 'Friday' },
      { value: 'sat', label: 'Saturday' },
      { value: 'sun', label: 'Sunday' },
    ],
  },
  {
    key: 'availability.openingTime',
    type: 'time' as const,
    label: 'Opening time',
    sectionId: 'availability',
  },
  {
    key: 'availability.closingTime',
    type: 'time' as const,
    label: 'Closing time',
    sectionId: 'availability',
  },
  {
    key: 'services.pricingStartsAt',
    type: 'currency' as const,
    label: 'Pricing starts at',
    sectionId: 'services',
  },
  {
    key: 'services.atLocation',
    type: 'boolean' as const,
    label: 'At-location service',
    sectionId: 'services',
  },
  {
    key: 'services.homeVisit',
    type: 'boolean' as const,
    label: 'Home visit available',
    sectionId: 'services',
  },
  {
    key: 'services.online',
    type: 'boolean' as const,
    label: 'Online service available',
    sectionId: 'services',
  },
];

export const GLOBAL_PROVIDER_FORM_SCHEMA: ProviderFormSchemaBody = {
  scope: 'global',
  providerKinds: ['business', 'individual'],
  version: 1,
  status: 'published',
  sections: commonSections,
  fields: commonFields,
};

function categorySchema(
  categoryId: string,
  sections: { id: string; title: string; sortOrder: number }[],
  fields: ProviderFormSchemaBody['fields'],
  providerKinds: ProviderFormSchemaBody['providerKinds'] = ['business', 'individual'],
): ProviderFormSchemaBody {
  return {
    scope: 'category',
    categoryId,
    providerKinds,
    version: 1,
    status: 'published',
    sections,
    fields,
  };
}

export const CATEGORY_PROVIDER_FORM_SCHEMAS: ProviderFormSchemaBody[] = [
  categorySchema('health.hospitals', [{ id: 'hospital', title: 'Hospital / clinic details', sortOrder: 10 }], [
    { key: 'hospital.registrationNumber', type: 'text', label: 'Hospital registration number', required: true, sectionId: 'hospital' },
    { key: 'hospital.departments', type: 'multiselect', label: 'Departments', sectionId: 'hospital', options: [
      { value: 'emergency', label: 'Emergency' },
      { value: 'icu', label: 'ICU' },
      { value: 'opd', label: 'OPD' },
      { value: 'diagnostics', label: 'Diagnostics' },
    ]},
    { key: 'hospital.emergencyAvailable', type: 'boolean', label: '24/7 emergency available', sectionId: 'hospital' },
    { key: 'hospital.consultationFee', type: 'currency', label: 'Consultation fee from', sectionId: 'hospital' },
    { key: 'hospital.facilities', type: 'textarea', label: 'Facilities & amenities', sectionId: 'hospital' },
  ], ['business']),
  categorySchema('health.doctors', [{ id: 'medical', title: 'Medical professional', sortOrder: 10 }], [
    { key: 'medical.qualification', type: 'text', label: 'Qualification', required: true, sectionId: 'medical' },
    { key: 'medical.registrationNumber', type: 'text', label: 'Medical registration number', required: true, sectionId: 'medical' },
    { key: 'medical.speciality', type: 'text', label: 'Speciality', required: true, sectionId: 'medical' },
    { key: 'medical.experienceYears', type: 'number', label: 'Years of experience', sectionId: 'medical' },
    { key: 'medical.consultationFee', type: 'currency', label: 'Consultation fee', sectionId: 'medical' },
    { key: 'medical.consultationDurationMins', type: 'number', label: 'Consultation duration (minutes)', sectionId: 'medical' },
  ], ['individual']),
  categorySchema('health.physiotherapist', [{ id: 'medical', title: 'Physiotherapy', sortOrder: 10 }], [
    { key: 'medical.qualification', type: 'text', label: 'Qualification', required: true, sectionId: 'medical' },
    { key: 'medical.registrationNumber', type: 'text', label: 'Registration number', sectionId: 'medical' },
    { key: 'medical.speciality', type: 'text', label: 'Speciality / focus area', sectionId: 'medical' },
    { key: 'medical.homeVisit', type: 'boolean', label: 'Home visit available', sectionId: 'medical' },
    { key: 'medical.sessionFee', type: 'currency', label: 'Session fee', sectionId: 'medical' },
  ], ['individual']),
  categorySchema('health.nursing', [{ id: 'medical', title: 'Nursing services', sortOrder: 10 }], [
    { key: 'medical.qualification', type: 'text', label: 'Qualification', required: true, sectionId: 'medical' },
    { key: 'medical.registrationNumber', type: 'text', label: 'Nursing council registration', sectionId: 'medical' },
    { key: 'medical.homeVisit', type: 'boolean', label: 'Home nursing available', sectionId: 'medical' },
    { key: 'medical.shiftRate', type: 'currency', label: 'Shift rate from', sectionId: 'medical' },
  ], ['individual']),
  categorySchema('fitness.gym', [{ id: 'gym', title: 'Gym details', sortOrder: 10 }], [
    { key: 'gym.equipment', type: 'textarea', label: 'Equipment & facilities', sectionId: 'gym' },
    { key: 'gym.trainersCount', type: 'number', label: 'Number of trainers', sectionId: 'gym' },
    { key: 'gym.membershipPlans', type: 'textarea', label: 'Membership plans', sectionId: 'gym' },
    { key: 'gym.genderSpecific', type: 'dropdown', label: 'Gender-specific availability', sectionId: 'gym', options: [
      { value: 'mixed', label: 'Mixed' },
      { value: 'men', label: 'Men only' },
      { value: 'women', label: 'Women only' },
    ]},
    { key: 'gym.photos', type: 'image', label: 'Gym photos', sectionId: 'gym' },
  ], ['business']),
  categorySchema('fitness.personal_trainer', [{ id: 'trainer', title: 'Personal training', sortOrder: 10 }], [
    { key: 'trainer.certifications', type: 'textarea', label: 'Certifications', required: true, sectionId: 'trainer' },
    { key: 'trainer.expertise', type: 'multiselect', label: 'Expertise', sectionId: 'trainer', options: [
      { value: 'strength', label: 'Strength' },
      { value: 'weight_loss', label: 'Weight loss' },
      { value: 'sports', label: 'Sports conditioning' },
      { value: 'rehab', label: 'Rehabilitation' },
    ]},
    { key: 'trainer.clientCapacity', type: 'number', label: 'Active client capacity', sectionId: 'trainer' },
    { key: 'trainer.packages', type: 'textarea', label: 'Training packages & pricing', sectionId: 'trainer' },
  ], ['individual']),
  categorySchema('course.school_tuition', [{ id: 'coaching', title: 'Coaching / tutoring', sortOrder: 10 }], [
    { key: 'coaching.subject', type: 'text', label: 'Subject or coaching type', required: true, sectionId: 'coaching' },
    { key: 'coaching.qualifications', type: 'textarea', label: 'Qualifications', sectionId: 'coaching' },
    { key: 'coaching.experienceYears', type: 'number', label: 'Years of experience', sectionId: 'coaching' },
    { key: 'coaching.mode', type: 'multiselect', label: 'Teaching mode', sectionId: 'coaching', options: [
      { value: 'online', label: 'Online' },
      { value: 'offline', label: 'Offline' },
      { value: 'hybrid', label: 'Hybrid' },
    ]},
    { key: 'coaching.batchCapacity', type: 'number', label: 'Batch capacity', sectionId: 'coaching' },
    { key: 'coaching.feeStructure', type: 'textarea', label: 'Fee structure', sectionId: 'coaching' },
  ], ['individual']),
  categorySchema('home.electrician', [{ id: 'homeservice', title: 'Home service business', sortOrder: 10 }], [
    { key: 'homeservice.teamSize', type: 'number', label: 'Team size', sectionId: 'homeservice' },
    { key: 'homeservice.serviceAreas', type: 'textarea', label: 'Service areas', required: true, sectionId: 'homeservice' },
    { key: 'homeservice.avgDurationMins', type: 'number', label: 'Average service duration (minutes)', sectionId: 'homeservice' },
    { key: 'homeservice.minimumCharge', type: 'currency', label: 'Minimum charge', sectionId: 'homeservice' },
    { key: 'homeservice.visitCharge', type: 'currency', label: 'Visit charge', sectionId: 'homeservice' },
  ], ['business', 'individual']),
  categorySchema('course.homemade', [{ id: 'food', title: 'Food provider', sortOrder: 10 }], [
    { key: 'food.menuDescription', type: 'textarea', label: 'Menu description', required: true, sectionId: 'food' },
    { key: 'food.mealPeriods', type: 'multiselect', label: 'Meal periods', sectionId: 'food', options: [
      { value: 'breakfast', label: 'Breakfast' },
      { value: 'lunch', label: 'Lunch' },
      { value: 'dinner', label: 'Dinner' },
      { value: 'snacks', label: 'Snacks' },
    ]},
    { key: 'food.deliveryAreas', type: 'textarea', label: 'Delivery locations', sectionId: 'food' },
    { key: 'food.subscriptionOptions', type: 'textarea', label: 'Subscription options', sectionId: 'food' },
    { key: 'food.leaveDays', type: 'multiselect', label: 'Weekly off days', sectionId: 'food', options: [
      { value: 'mon', label: 'Monday' },
      { value: 'tue', label: 'Tuesday' },
      { value: 'wed', label: 'Wednesday' },
      { value: 'thu', label: 'Thursday' },
      { value: 'fri', label: 'Friday' },
      { value: 'sat', label: 'Saturday' },
      { value: 'sun', label: 'Sunday' },
    ]},
  ], ['business', 'individual']),
];
